[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
  bblanchon/ArduinoJson
  mathieucarbou/ESPAsyncWebServer
  alanswx/ESPAsyncWiFiManager
  ezTime
monitor_speed = 115200
upload_protocol = esptool

[env:ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.123.142
upload_flags =
    --auth=${sysenv.OTA_PASSWORD}
